In [1]:
!pip install numpy

In [1]:
!conda update numpy

Solving environment: ...working... done

# All requested packages already installed.





==> WARNING: A newer version of conda exists. <==
  current version: 4.5.11
  latest version: 4.5.12

Please update conda by running

    $ conda update -n base -c defaults conda




In [1]:
import numpy as np
a = np.array([1,2,3,4.0])
print('shape of array a is ' + str(a.shape))
print('dimension of array a is '+ str(a.ndim)) #1d array
b = np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])
print('shape of array b is' + str(b.shape))
print('dimension of array b is '+ str(b.ndim))#2d array
print('size of array a is '+ str(a.size))
print('size of array b is '+ str(b.size))
print('data type of elements of array a is '+ str(a.dtype))
print('data type of elements of array b is '+ str(b.dtype))
print('number of bytes of array a are ' + str(a.itemsize))
print('number of bytes of array b are ' + str(b.itemsize))

shape of array a is (4,)
dimension of array a is 1
shape of array b is(2, 3)
dimension of array b is 2
size of array a is 4
size of array b is 6
data type of elements of array a is float64
data type of elements of array b is float64
number of bytes of array a are 8
number of bytes of array b are 8


In [27]:
a = np.array(range(1,5))
print('original shape of array is '+str(a.shape))
a = a.reshape((2,2)) #a = np.reshape(a,(2,2))
print(a.shape)

original shape of array is (4,)
(2, 2)


In [33]:
a = np.empty((2,2),dtype='int8')
print(a)
b = np.ones((2,2)) #similarly np.zeros
print(b)
c = np.eye(2)
print(c)
d = np.full((2,2),7)
print(d)

[[1 0]
 [0 1]]
[[1. 1.]
 [1. 1.]]
[[1. 0.]
 [0. 1.]]
[[7 7]
 [7 7]]


In [36]:
a = np.arange(1,4)
print(a)
b = np.arange(1,6,2,dtype='float32')
print(b)

[1 2 3]
[1. 3. 5.]


In [39]:
a = np.linspace(1,4,7)
print(a)
b = np.logspace(0,2,10) #array from 10^0 to 10^2 divided into 10 parts
print(b)

[1.  1.5 2.  2.5 3.  3.5 4. ]
[  1.           1.66810054   2.7825594    4.64158883   7.74263683
  12.91549665  21.5443469   35.93813664  59.94842503 100.        ]


In [42]:
a = np.array([[1,2,3],[4,5,6]])
print(a[:2,:2])
mask = a>3
print(mask)

[[1 2]
 [4 5]]
[[False False False]
 [ True  True  True]]


In [46]:
a = np.array([1,2,3+5j])
real_mask = np.isreal(a) #similarly iscomplex()
print(real_mask)
real_array = a[real_mask]
print(real_array)

[ True  True False]
[1.+0.j 2.+0.j]


In [50]:
a = np.arange(1,5).reshape(2,2)
print(a)
a = a.flatten()
print(a)

[[1 2]
 [3 4]]
[1 2 3 4]


In [53]:
z = np.random.random((5,5))
print(z)
zmax = a.max()
zmin = a.min()
znorm = (z-zmin)/(zmax-zmin)
print(znorm)


[[0.6768216  0.17415812 0.85453542 0.61342115 0.31702144]
 [0.18708346 0.71820838 0.66471155 0.85987765 0.66059777]
 [0.65809545 0.8435525  0.13286697 0.55975634 0.53262266]
 [0.79243191 0.37461154 0.23079718 0.65984449 0.91025244]
 [0.96276706 0.27292279 0.27340882 0.23956404 0.95992493]]
[[-0.10772613 -0.27528063 -0.04848819 -0.12885962 -0.22765952]
 [-0.27097218 -0.09393054 -0.11176282 -0.04670745 -0.11313408]
 [-0.11396818 -0.05214917 -0.28904434 -0.14674789 -0.15579245]
 [-0.06918936 -0.20846282 -0.25640094 -0.11338517 -0.02991585]
 [-0.01241098 -0.24235907 -0.24219706 -0.25347865 -0.01335836]]


In [59]:
#solving quadratic equation
coeff = [1,-4,4]
roots = np.roots(coeff)
print(roots)


[2. 2.]


In [63]:
#solving system of equations Ax=B
A = np.array([[2,1,2],[3,0,1],[1,1,-1]])
b = np.array([-3,5,-2])
x = np.linalg.solve(A,b)
print(x)
check_eq = np.allclose(A*x,b)
print(check_eq)


[ 2. -5. -1.]
False


In [3]:
#getting index of max value
A = np.array([[2,1,2],[3,0,1],[1,1,-1]])
idx = np.unravel_index(np.argmax(A),A.shape)
print(idx)

(1, 0)


In [4]:
A = np.c_[np.array([1,2,3]),np.array([4,5,6])]
print(A)
print(np.array([1,2,3]).shape)
#np.array([1,2,3]) is 3,1(in mind), shape of resultant array is 3,(1+1) i.e 3,2 stacking along second axis

[[1 4]
 [2 5]
 [3 6]]
(3,)


In [7]:
A = np.c_[np.array([[1,2,3]]),0,0]
print(A)
print(np.array([[1,2,3]]).shape)
#shape (1,3) of array, shape of 0 is 1,1 so resultant shape is 1,3+1+1

[[1 2 3 0 0]]
(1, 3)
